version: 2

aliases:
  - &setup_miniconda_prev
    name: setup_miniconda_prev
    command: |
       mkdir -p workspace
       git clone -b validateNightly https://github.com/CDAT/cdat.git workspace/cdat
       ###### install_miniconda.py installs miniconda3 under $WORKDIR/miniconda
       python workspace/cdat/scripts/install_miniconda.py -w $WORKDIR -p 'py3'
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       conda config --set always_yes yes
       conda config --add channels conda-forge --force
       conda config --set channel_priority strict
       conda install -n base -c conda-forge conda-build anaconda-client conda-smithy conda-verify conda-forge-pinning conda-forge-build-setup conda-forge-ci-setup
       conda config --set anaconda_upload no

  - &setup_miniconda
    name: setup_miniconda
    environment:
       CONDA_URL: "https://repo.continuum.io/miniconda"
    command: |
       mkdir -p workspace
       if [[ `uname` == Linux ]]; then
          yum install -y git wget mega-libGL-devel
          mkdir -p $WORKDIR
          wget $CONDA_URL/$MINICONDA -O $WORKDIR/$MINICONDA
       else
          curl $CONDA_URL/$MINICONDA -o $WORKDIR/$MINICONDA
       fi
       bash $WORKDIR/$MINICONDA -b -p $WORKDIR/miniconda

       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       conda config --set always_yes yes
       conda config --add channels conda-forge --force
       conda config --set channel_priority strict
       conda install -n base -c conda-forge conda-build anaconda-client conda-smithy conda-verify conda-forge-pinning conda-forge-build-setup conda-forge-ci-setup
       conda config --set anaconda_upload no


  - &conda_rerender
    name: conda_rerender
    command: |
       echo "xxx conda_rerender xxx"
       git clone https://github.com/CDAT/conda-recipes.git $WORKDIR/conda-recipes 
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base

       git clone -b dev https://github.com/muryanto1/vtk-feedstock.git $WORKDIR/vtk-feedstock
       cd $WORKDIR/vtk-feedstock
       conda smithy rerender
       ls -l .ci_support      

  - &conda_build
     name: conda_build
     command: |
        source $WORKDIR/miniconda/etc/profile.d/conda.sh
        conda activate base
        conda config --add channels conda-forge --force
        conda config --add channels cdat/label/nightly --force
        conda config --set channel_priority strict
        cd $WORKDIR/vtk-feedstock
        conda build -m .ci_support/${VARIANT}.yaml recipe/

jobs:
   macos_setup:
      macos:
         xcode: "11.3.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         MINICONDA: "Miniconda3-latest-MacOSX-x86_64.sh"
      steps:
         - checkout
         - run: *setup_miniconda
         - run: *conda_rerender
         - persist_to_workspace:
              root: 
              paths: 
                 - macos_build

   linux_setup:
      docker:
         - image: condaforge/linux-anvil-comp7
      environment:
         WORKDIR: /home/circleci/project/linux_build
         MINICONDA: "Miniconda3-latest-Linux-x86_64.sh"
      steps:
         - checkout
         - run: yum install -y git wget
         - run: *setup_miniconda
         - run: *conda_rerender
         - persist_to_workspace:
              root: /home/circleci/project
              paths:
                 - linux_build

   osx_VTK_WITH_OSMESAFalsepython3.7:
      macos:
         xcode: "11.3.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         VARIANT: "osx_VTK_WITH_OSMESAFalsepython3.7"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build

   osx_VTK_WITH_OSMESATruepython3.7:
      macos:
         xcode: "11.3.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         VARIANT: "osx_VTK_WITH_OSMESATruepython3.7"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build

   linux_VTK_WITH_OSMESAFalsepython3.7:
      docker:
         - image: condaforge/linux-anvil-comp7
      environment:
         WORKDIR: /home/circleci/project/linux_build
         VARIANT: "linux_VTK_WITH_OSMESAFalsepython3.7"
      steps:
         - checkout
         - run: mkdir -p /home/circleci/project
         - attach_workspace:
              at: /home/circleci/project
         - run: yum install -y mega-libGL-devel
         - run: *conda_build

   linux_VTK_WITH_OSMESATruepython3.7:
      docker:
         - image: condaforge/linux-anvil-comp7
      environment:
         WORKDIR: /home/circleci/project/linux_build
         VARIANT: "linux_VTK_WITH_OSMESATruepython3.7"
      steps:
         - checkout
         - run: mkdir -p /home/circleci/project
         - attach_workspace:
              at: /home/circleci/project
         - run: yum install -y mega-libGL-devel
         - run: *conda_build

workflows:
   version: 2
   vtk:
      jobs:
         #- macos_setup
         - linux_setup
         #- osx_VTK_WITH_OSMESAFalsepython3.7:
         #     requires:
         #        - macos_setup
         #- osx_VTK_WITH_OSMESATruepython3.7:
         #     requires:
         #        - macos_setup
         - linux_VTK_WITH_OSMESAFalsepython3.7:
              requires:
                 - linux_setup
         - linux_VTK_WITH_OSMESATruepython3.7:
              requires:
                 - linux_setup
