version: 2

aliases:
  - &setup_miniconda
    name: setup_miniconda
    command: |
       mkdir -p workspace
       git clone -b validateNightly git@github.com:CDAT/cdat workspace/cdat
       ## install_miniconda.py installs miniconda3 under $WORKDIR/miniconda
       python workspace/cdat/scripts/install_miniconda.py -w $WORKDIR -p 'py3'
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       conda config --set always_yes yes
       conda config --add channels conda-forge --force
       conda config --set channel_priority strict
       conda install -n base -c conda-forge conda-build anaconda-client conda-smithy conda-verify conda-forge-pinning conda-forge-build-setup conda-forge-ci-setup
       conda config --set anaconda_upload no

  - &conda_rerender
    name: conda_rerender
    command: |
       git clone https://github.com/CDAT/conda-recipes.git $WORKDIR/conda-recipes 
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base

       git clone -b dev https://github.com/muryanto1/vtk-feedstock.git $WORKDIR/vtk-feedstock
       cd $WORKDIR/vtk-feedstock
       conda smithy rerender
       ls -l .ci_support      

 - &conda_build
    name: conda_build
    command: |
       source $WORKDIR/miniconda/etc/profile.d/conda.sh
       conda activate base
       conda config --add channels conda-forge --force
       conda config --add channels cdat/label/nightly --force
       conda config --set channel_priority strict
       cd $WORKDIR/vtk-feedstock
       conda build -m .ci_support/${VARIANT}.yaml recipe/

jobs:
   macos_setup:
      macos:
         xcode: "11.3.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
      steps:
         - checkout
         - run: *setup_miniconda
         - run: *conda_rerender
         - persist_to_workspace:
              root: .
              paths: 
                 - macos_build

   linux_setup:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
      steps:
         - checkout
         - run: *setup_miniconda
         - run: *conda_rerender
         - persist_to_workspace:
              root: .
              paths:
                 - linux_build

   osx_VTK_WITH_OSMESAFalsepython3.7:
      macos:
         xcode: "11.3.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         VARIANT: "osx_VTK_WITH_OSMESAFalsepython3.7"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build

   ##
   osx_VTK_WITH_OSMESATruepython3.7:
      macos:
         xcode: "11.3.0"
      environment:
         WORKDIR: /Users/distiller/project/macos_build
         VARIANT: "osx_VTK_WITH_OSMESATruepython3.7"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build

   linux_VTK_WITH_OSMESAFalsepython3.7:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         VARIANT: "linux_VTK_WITH_OSMESAFalsepython3.7"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build

   linux_VTK_WITH_OSMESATruepython3.7:
      machine:
         image: circleci/classic:latest
      environment:
         WORKDIR: /home/circleci/project/linux_build
         VARIANT: "linux_VTK_WITH_OSMESATruepython3.7"
      steps:
         - checkout
         - attach_workspace:
              at: .
         - run: *conda_build

workflows:
   version: 2
   vtk:
      jobs:
         - macos_setup
         - linux_setup
         - osx_VTK_WITH_OSMESAFalsepython3.7:
           requires:
              - macos_setup
         - osx_VTK_WITH_OSMESATruepython3.7:
           requires:
              - macos_setup
         - linux_VTK_WITH_OSMESAFalsepython3.7:
           requires:
              - linux_setup
         - linux_VTK_WITH_OSMESATruepython3.7:
           requires:
              - linux_setup
